"""
Crisis detection - trained ML model (from Seminar_2 sub-project) + fast
keyword backup layer.

The ML model (TF-IDF word + character n-grams -> Logistic Regression,
trained on 1,109 labeled messages) does the real understanding: it
correctly distinguishes "I want to kill myself" from "I don't want to
kill myself" because the training data explicitly teaches that
distinction, not because of a hand-written negation rule. It also
generalizes to phrasing that never used the word "not" at all, e.g.
"I don't want to live anymore" is correctly flagged as crisis even
though it contains "don't", because the model learned that specific
phrase pattern from data - something a simple negation-window regex
could never get right.

The model is loaded ONCE, the first time is_crisis() is called, and
cached in memory for the rest of the app's lifetime - this is what makes
per-message inference fast (~1ms), not the model itself being "fast" to
load (it takes ~1-2 seconds once, which is negligible amortized across
a running app).

A fast keyword layer runs alongside the ML model as a backup: if either
flags the message, it's treated as crisis. This matters because no ML
model is perfect - testing showed borderline/missed cases on heavily
misspelled input (e.g. "kill mysekf" scored only ~27%), so the keyword
layer catches the most obvious explicit cases even when the ML model is
uncertain.
"""
import os
import re
import pickle

MODEL_PATH = os.path.join(
    os.path.dirname(__file__), "crisis_model", "crisis_detection_model.pkl"
)

# Below this probability, the ML model does not consider it crisis.
# Set slightly below the model's own 0.50 default to bias toward catching
# more real crises at the cost of a few more false positives - the right
# tradeoff for a safety feature (a missed crisis is far worse than an
# unnecessary SOS redirect).
ML_THRESHOLD = 0.40

# Deliberately general, non-exhaustive set of high-signal terms - the
# fast backup layer for obvious explicit cases.
CRISIS_KEYWORDS = [
    r"\bsuicid\w*\b",
    r"\bkill(ing)?\s+myself\b",
    r"\bend(ing)?\s+my\s+life\b",
    r"\bself[\s-]?harm\w*\b",
    r"\bhurt(ing)?\s+myself\b",
]
_KEYWORD_PATTERN = re.compile("|".join(CRISIS_KEYWORDS), re.IGNORECASE)

NEGATION_WORDS = {
    "not", "no", "never", "cannot", "cant", "wont", "wouldnt", "dont",
    "doesnt", "didnt", "isnt", "wasnt", "arent", "werent", "stopped",
    "quit", "against", "refuse",
}
NEGATION_WINDOW = 4


def _tokenize(text):
    return re.findall(r"[a-z]+", text.lower().replace("'", ""))


def _keyword_flag(message: str) -> bool:
    """
    Keyword layer, but negation-aware: a match immediately preceded by a
    negation word ("I don't want to kill myself") is NOT flagged, so this
    layer can't override the ML model's more nuanced verdict on exactly
    the case it's meant to get right.
    """
    text_lower = message.lower()
    for pattern in CRISIS_KEYWORDS:
        for m in re.finditer(pattern, text_lower):
            preceding = _tokenize(text_lower[: m.start()])[-NEGATION_WINDOW:]
            if not any(tok in NEGATION_WORDS for tok in preceding):
                return True
    return False

_features = None
_model = None


def clean_text(text):
    """Must exactly match the preprocessing used in Crisis_detection.py's training script."""
    text = str(text).lower().strip()
    text = text.replace("don't", "do not").replace("dont", "do not")
    text = text.replace("can't", "cannot").replace("cant", "cannot")
    text = text.replace("won't", "will not").replace("wont", "will not")
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def _load_model():
    global _features, _model
    if _model is not None:
        return
    with open(MODEL_PATH, "rb") as f:
        saved = pickle.load(f)
    _features = saved["features"]
    _model = saved["model"]


def crisis_probability(message: str) -> float:
    """Returns the ML model's crisis probability (0-1) for a message."""
    _load_model()
    cleaned = clean_text(message)
    if not cleaned:
        return 0.0
    vector = _features.transform([cleaned])
    return float(_model.predict_proba(vector)[0][1])


def is_crisis(message: str) -> bool:
    """True if EITHER the negation-aware keyword layer or the ML model flags the message."""
    if not message:
        return False
    if _keyword_flag(message):
        return True
    return crisis_probability(message) >= ML_THRESHOLD


# Fixed, caring response shown immediately when crisis is detected.
# Never generated by the AI model - always this exact, reviewed text.
CRISIS_RESPONSE = (
    "It sounds like you're going through something really painful right now, "
    "and I'm really glad you told me. I'm not able to provide the kind of "
    "support you may need for this, so I'm taking you to our crisis "
    "resources page now - please reach out to one of the helplines there "
    "right away. If you're in immediate danger, please contact emergency "
    "services. You deserve support from someone who can really help."
)


# Fixed, caring response shown immediately when crisis is detected.
# Never generated by the AI model - always this exact, reviewed text.
CRISIS_RESPONSE = (
    "It sounds like you're going through something really painful right now, "
    "and I'm really glad you told me. I'm not able to provide the kind of "
    "support you may need for this, so I'm taking you to our crisis "
    "resources page now - please reach out to one of the helplines there "
    "right away. If you're in immediate danger, please contact emergency "
    "services. You deserve support from someone who can really help."
)
